services:
  # Development services
  postgres:
    image: postgres:16.3
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: rubbit_server
      POSTGRES_PASSWORD: "3qaOC8m8cdLKoRY1XqAaiPI1S4rWEzzV"
    volumes:
      - rubbit_server_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "GMHy3_bY9J4W1UElN0N-0x27OoKqsL7F"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: postgres:16.3
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: rubbit_server_test
      POSTGRES_PASSWORD: "LHlU87uybjqCiSMBYpZmm2oYv0tgDcA6"
    volumes:
      - rubbit_server_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "E8F1ho3NfOvNvlqpMXT13Rs264NJPDyZ"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  rubbit_server_data:
  rubbit_server_test_data:
